### ISSUE TITLE
Oddaja naloge

### ISSUE THREAD

**Issue by mateabt** [mateabt/APPR-2020-21#3]
Pozdravljeni,
mislim, da sem  končala , zato bi oddala svoj projekt. Če je kaj za popravit oz. dodat mi prosim sporočite.
Hvala in lep pozdrav, Matea

**Comment by jaanos** [comment]
Glede na to, da projekt deluje, bom dodal povezavo na repozitorij za zagovore, tako da se lahko z @alenFMF domeniš za termin zagovora. Če boš do takrat še kaj spreminjala, mi javi, da posodobim povezavo.

Razlog, zakaj animacija ne deluje na Binderju, je ta, da se razpredelnica `BDP` ne uvozi pravilno - očitno se funkcija `as.numeric` v novejših različicah R-ja obnaša drugače. Da bo delovalo, lahko celoten uvoz narediš tako:
```R
  BDP <- read_tsv('podatki/BDP.tsv') %>% select(-1) %>%
    pivot_longer(everything(), names_to='leto', values_to='BDP',
                 names_transform=c(leto=parse_number))
```

Imam še sledeči pripombi:
* Na grafu `graf_gib` bi bilo dobro poskrbeti za ustrezen izpis števil na osi y (tako kot na drugih grafih), ali pa, še bolje, podatke prikazati v milijardah, da številke ne bodo prevelike (podobno lahko narediš tudi drugod).
* Na `graf.napoved1` bi bilo dobro napovedane točke prikazati drugače od dejanskih podatkov (podobno kot narediš pri zadnjem grafu).

**Comment by mateabt** [comment]
sem spremenila uvoz ter grafe ,tako da bi prosila za posodobitev povezave.
Hvala

**Comment by jaanos** [comment]
V redu, sem poodobil.
